MERGE dbo.PropertyType AS TARGET
USING (VALUES (19, 1, 46, 'Apartment'),
              (20, 1, 47, 'Barn'),
              (21, 1, 48, 'Bed & Breakfast'),
              (22, 1, 49, 'Boat'),
              (23, 1, 50, 'Building'),
              (24, 1, 51, 'Bungalow'),
              (25, 1, 52, 'Cabin'),
              (26, 1, 53, 'Campground'),
              (27, 1, 54, 'Caravan'),
              (28, 1, 55, 'Castle'),
              (29, 1, 56, 'Chalet'),
              (30, 1, 57, 'Chateau / Country House'),
              (31, 1, 58, 'Chácara/sítio'),
              (32, 1, 59, 'Condo'),
              (33, 1, 60, 'Corporate Apartment'),
              (34, 1, 61, 'Cottage'),
              (35, 1, 62, 'Estate'),
              (36, 1, 63, 'Farmhouse'),
              (37, 1, 64, 'Hotel'),
              (38, 1, 65, 'Hotel Suites'),
              (39, 1, 66, 'House'),
              (40, 1, 67, 'House Boat'),
              (41, 1, 68, 'Lodge'),
              (42, 1, 69, 'Mas'),
              (43, 1, 70, 'Mill'),
              (44, 1, 71, 'Mobile Home'),
              (45, 1, 72, 'Recreational Vehicle'),
              (46, 1, 73, 'Resort'),
              (47, 1, 74, 'Riad'),
              (48, 1, 75, 'Studio'),
              (49, 1, 76, 'Tower'),
              (50, 1, 77, 'Townhome'),
              (51, 1, 78, 'Villa'),
              (52, 1, 79, 'Yacht'))
AS SOURCE (PropertyTypeId,
           IsActive,
           LabelId,
           PropertyTypeName)
ON TARGET.PropertyTypeId = SOURCE.PropertyTypeId
WHEN MATCHED THEN UPDATE SET TARGET.PropertyTypeName = SOURCE.PropertyTypeName,
                             TARGET.LabelId          = SOURCE.LabelId,
                             TARGET.IsActive         = SOURCE.IsActive
WHEN NOT MATCHED THEN INSERT (PropertyTypeId,
                              PropertyTypeName,
                              LabelId,
                              IsActive)
                      VALUES (PropertyTypeId,
                              PropertyTypeName,
                              LabelId,
                              IsActive);