MERGE dbo.Country AS TARGET
USING (VALUES ('AD', 1, 1, 'Andorra', 'parish'),
              ('AE', 1, 1, 'United Arab Emirates', 'emirate'),
              ('AF', 1, 1, 'Afghanistan', 'province'),
              ('AG', 1, 1, 'Antigua and Barbuda', 'dependency'),
              ('AI', 1, 0, 'Anguilla', NULL),
              ('AL', 1, 1, 'Albania', 'county'),
              ('AM', 1, 1, 'Armenia', 'region'),
              ('AO', 1, 1, 'Angola', 'province'),
              ('AQ', 1, 0, 'Antarctica', NULL),
              ('AR', 1, 1, 'Argentina', 'province'),
              ('AS', 1, 0, 'American Samoa', NULL),
              ('AT', 1, 1, 'Austria', 'state'),
              ('AU', 1, 1, 'Australia', 'territory'),
              ('AW', 1, 0, 'Aruba', NULL),
              ('AX', 1, 0, 'Åland Islands', NULL),
              ('AZ', 1, 1, 'Azerbaijan', 'rayon'),
              ('BA', 1, 1, 'Bosnia and Herzegovina', 'entity'),
              ('BB', 1, 1, 'Barbados', 'parish'),
              ('BD', 1, 1, 'Bangladesh', 'district'),
              ('BE', 1, 1, 'Belgium', 'province'),
              ('BF', 1, 1, 'Burkina Faso', 'province'),
              ('BG', 1, 1, 'Bulgaria', 'district'),
              ('BH', 1, 1, 'Bahrain', 'governorate'),
              ('BI', 1, 1, 'Burundi', 'province'),
              ('BJ', 1, 1, 'Benin', 'department'),
              ('BL', 1, 0, 'Saint Barthélemy', NULL),
              ('BM', 1, 0, 'Bermuda', NULL),
              ('BN', 1, 1, 'Brunei Darussalam', 'department'),
              ('BO', 1, 1, 'Bolivia (Plurinational State of)', 'department'),
              ('BQ', 1, 1, 'Bonaire, Sint Eustatius and Saba', 'special municipality'),
              ('BR', 1, 1, 'Brazil', 'state'),
              ('BS', 1, 1, 'Bahamas', 'district'),
              ('BT', 1, 1, 'Bhutan', 'district'),
              ('BV', 1, 0, 'Bouvet Island', NULL),
              ('BW', 1, 1, 'Botswana', 'district'),
              ('BY', 1, 1, 'Belarus', 'oblast'),
              ('BZ', 1, 1, 'Belize', 'district'),
              ('CA', 1, 1, 'Canada', 'province'),
              ('CC', 1, 0, 'Cocos (Keeling) Islands', NULL),
              ('CD', 1, 1, 'Congo (Democratic Republic of the)', 'province'),
              ('CF', 1, 1, 'Central African Republic', 'prefecture'),
              ('CG', 1, 1, 'Congo', 'department'),
              ('CH', 1, 1, 'Switzerland', 'canton'),
              ('CI', 1, 1, 'Côte d''Ivoire', 'autonomous district'),
              ('CK', 1, 0, 'Cook Islands', NULL),
              ('CL', 1, 1, 'Chile', 'region'),
              ('CM', 1, 1, 'Cameroon', 'region'),
              ('CN', 1, 1, 'China', 'province'),
              ('CO', 1, 1, 'Colombia', 'department'),
              ('CR', 1, 1, 'Costa Rica', 'province'),
              ('CU', 1, 1, 'Cuba', 'province'),
              ('CV', 1, 1, 'Cabo Verde', 'municipality'),
              ('CW', 1, 0, 'Curaçao', NULL),
              ('CX', 1, 0, 'Christmas Island', NULL),
              ('CY', 1, 1, 'Cyprus', 'district'),
              ('CZ', 1, 1, 'Czech Republic', 'district'),
              ('DE', 1, 1, 'Germany', 'Land'),
              ('DJ', 1, 1, 'Djibouti', 'region'),
              ('DK', 1, 1, 'Denmark', 'region'),
              ('DM', 1, 1, 'Dominica', 'parish'),
              ('DO', 1, 1, 'Dominican Republic', 'province'),
              ('DZ', 1, 1, 'Algeria', 'province'),
              ('EC', 1, 1, 'Ecuador', 'province'),
              ('EE', 1, 1, 'Estonia', 'county'),
              ('EG', 1, 1, 'Egypt', 'governorate'),
              ('EH', 1, 1, 'Western Sahara', NULL),
              ('ER', 1, 1, 'Eritrea', 'region'),
              ('ES', 1, 1, 'Spain', 'province'),
              ('ET', 1, 1, 'Ethiopia', 'administration'),
              ('FI', 1, 1, 'Finland', 'region'),
              ('FJ', 1, 1, 'Fiji', 'province'),
              ('FK', 1, 0, 'Falkland Islands (Malvinas)', NULL),
              ('FM', 1, 1, 'Micronesia (Federated States of)', 'state'),
              ('FO', 1, 0, 'Faroe Islands', NULL),
              ('FR', 1, 1, 'France', 'metropolitan department'),
              ('GA', 1, 0, 'Gabon', NULL),
              ('GB', 1, 1, 'United Kingdom of Great Britain and Northern Ireland', 'council area'),
              ('GD', 1, 1, 'Grenada', 'parish'),
              ('GE', 1, 1, 'Georgia', 'autonomous republic'),
              ('GF', 1, 0, 'French Guiana', NULL),
              ('GG', 1, 0, 'Guernsey', NULL),
              ('GH', 1, 1, 'Ghana', 'region'),
              ('GI', 1, 0, 'Gibraltar', NULL),
              ('GL', 1, 1, 'Greenland', 'municipality'),
              ('GM', 1, 1, 'Gambia', 'city'),
              ('GN', 1, 1, 'Guinea', 'prefecture'),
              ('GP', 1, 0, 'Guadeloupe', NULL),
              ('GQ', 1, 1, 'Equatorial Guinea', 'province'),
              ('GR', 1, 1, 'Greece', 'administrative region'),
              ('GS', 1, 0, 'South Georgia and the South Sandwich Islands', NULL),
              ('GT', 1, 1, 'Guatemala', ''),
              ('GU', 1, 0, 'Guam', NULL),
              ('GW', 1, 1, 'Guinea-Bissau', 'region'),
              ('GY', 1, 1, 'Guyana', 'region'),
              ('HK', 1, 0, 'Hong Kong', NULL),
              ('HM', 1, 0, 'Heard Island and McDonald Islands', NULL),
              ('HN', 1, 1, 'Honduras', 'department'),
              ('HR', 1, 0, 'Croatia', '"county".'),
              ('HT', 1, 1, 'Haiti', ''),
              ('HU', 1, 1, 'Hungary', 'county'),
              ('ID', 1, 1, 'Indonesia', 'province'),
              ('IE', 1, 1, 'Ireland', 'province'),
              ('IL', 1, 1, 'Israel', 'district'),
              ('IM', 1, 0, 'Isle of Man', NULL),
              ('IN', 1, 1, 'India', 'Union territory'),
              ('IO', 1, 0, 'British Indian Ocean Territory', NULL),
              ('IQ', 1, 1, 'Iraq', 'governorate'),
              ('IR', 1, 1, 'Iran (Islamic Republic of)', 'province'),
              ('IS', 1, 1, 'Iceland', 'region'),
              ('IT', 1, 1, 'Italy', 'region'),
              ('JE', 1, 1, 'Jersey', NULL),
              ('JM', 1, 0, 'Jamaica', 'parish'),
              ('JO', 1, 1, 'Jordan', 'governorate'),
              ('JP', 1, 1, 'Japan', 'prefecture'),
              ('KE', 1, 1, 'Kenya', 'county'),
              ('KG', 1, 1, 'Kyrgyzstan', 'region'),
              ('KH', 1, 1, 'Cambodia', 'province'),
              ('KI', 1, 1, 'Kiribati', 'group of islands'),
              ('KM', 1, 1, 'Comoros', 'island'),
              ('KN', 1, 1, 'Saint Kitts and Nevis', 'parish'),
              ('KP', 1, 1, 'Korea (Democratic People''s Republic of)', 'province'),
              ('KR', 1, 1, 'Korea (Republic of)', 'metropolitan city'),
              ('KW', 1, 1, 'Kuwait', 'governorate'),
              ('KY', 1, 0, 'Cayman Islands', NULL),
              ('KZ', 1, 1, 'Kazakhstan', 'region'),
              ('LA', 1, 1, 'Lao People''s Democratic Republic', 'province'),
              ('LB', 1, 1, 'Lebanon', 'governorate'),
              ('LC', 1, 1, 'Saint Lucia', 'district'),
              ('LI', 1, 1, 'Liechtenstein', 'commune'),
              ('LK', 1, 1, 'Sri Lanka', 'province'),
              ('LR', 1, 1, 'Liberia', 'county'),
              ('LS', 1, 1, 'Lesotho', 'district'),
              ('LT', 1, 1, 'Lithuania', 'district municipality'),
              ('LU', 1, 1, 'Luxembourg', 'canton'),
              ('LV', 1, 1, 'Latvia', 'municipality'),
              ('LY', 1, 1, 'Libya', 'popularate'),
              ('MA', 1, 1, 'Morocco', 'prefecture'),
              ('MC', 1, 1, 'Monaco', 'quarter'),
              ('MD', 1, 1, 'Moldova (Republic of)', 'district'),
              ('ME', 1, 1, 'Montenegro', 'municipality'),
              ('MF', 1, 0, 'Saint Martin (French part)', NULL),
              ('MG', 1, 1, 'Madagascar', 'province'),
              ('MH', 1, 1, 'Marshall Islands', 'municipality'),
              ('MK', 1, 1, 'North Macedonia', 'municipality'),
              ('ML', 1, 1, 'Mali', 'district'),
              ('MM', 1, 1, 'Myanmar', 'region'),
              ('MN', 1, 1, 'Mongolia', 'province'),
              ('MO', 1, 0, 'Macao', NULL),
              ('MP', 1, 0, 'Northern Mariana Islands', NULL),
              ('MQ', 1, 1, 'Martinique', NULL),
              ('MR', 1, 1, 'Mauritania', 'region'),
              ('MS', 1, 1, 'Montserrat', NULL),
              ('MT', 1, 1, 'Malta', 'local council'),
              ('MU', 1, 1, 'Mauritius', 'dependency'),
              ('MV', 1, 0, 'Maldives', 'administrative atoll'),
              ('MW', 1, 0, 'Malawi', 'district'),
              ('MX', 1, 1, 'Mexico', 'state'),
              ('MY', 1, 1, 'Malaysia', 'state'),
              ('MZ', 1, 1, 'Mozambique', 'province'),
              ('NA', 1, 1, 'Namibia', 'region'),
              ('NC', 1, 0, 'New Caledonia', NULL),
              ('NE', 1, 1, 'Niger', 'region'),
              ('NF', 1, 0, 'Norfolk Island', NULL),
              ('NG', 1, 1, 'Nigeria', 'state'),
              ('NI', 1, 1, 'Nicaragua', 'department'),
              ('NL', 1, 1, 'Netherlands', 'province'),
              ('NO', 1, 1, 'Norway', 'county'),
              ('NP', 1, 1, 'Nepal', 'province'),
              ('NR', 1, 1, 'Nauru', 'district'),
              ('NU', 1, 0, 'Niue', NULL),
              ('NZ', 1, 1, 'New Zealand', 'region'),
              ('OM', 1, 1, 'Oman', 'governorate'),
              ('PA', 1, 1, 'Panama', 'province'),
              ('PE', 1, 1, 'Peru', 'region'),
              ('PF', 1, 1, 'French Polynesia', NULL),
              ('PG', 1, 1, 'Papua New Guinea', 'autonomous region'),
              ('PH', 1, 1, 'Philippines', 'region'),
              ('PK', 1, 1, 'Pakistan', 'province'),
              ('PL', 1, 1, 'Poland', 'voivodship'),
              ('PM', 1, 0, 'Saint Pierre and Miquelon', NULL),
              ('PN', 1, 0, 'Pitcairn', NULL),
              ('PR', 1, 1, 'Puerto Rico', NULL),
              ('PS', 1, 1, 'Palestine, State of', 'governorate'),
              ('PT', 1, 1, 'Portugal', 'district'),
              ('PW', 1, 1, 'Palau', 'state'),
              ('PY', 1, 1, 'Paraguay', 'department'),
              ('QA', 1, 1, 'Qatar', 'municipality'),
              ('RE', 1, 0, 'Réunion', NULL),
              ('RO', 1, 1, 'Romania', 'department'),
              ('RS', 1, 1, 'Serbia', 'city'),
              ('RU', 1, 1, 'Russian Federation', 'republic'),
              ('RW', 1, 1, 'Rwanda', 'city'),
              ('SA', 1, 1, 'Saudi Arabia', 'region'),
              ('SB', 1, 1, 'Solomon Islands', 'capital territory'),
              ('SC', 1, 1, 'Seychelles', 'district'),
              ('SD', 1, 1, 'Sudan', 'state'),
              ('SE', 1, 1, 'Sweden', 'county'),
              ('SG', 1, 1, 'Singapore', 'district'),
              ('SH', 1, 1, 'Saint Helena, Ascension and Tristan da Cunha', 'island'),
              ('SI', 1, 1, 'Slovenia', 'municipality'),
              ('SJ', 1, 0, 'Svalbard and Jan Mayen', NULL),
              ('SK', 1, 1, 'Slovakia', 'region'),
              ('SL', 1, 1, 'Sierra Leone', 'province'),
              ('SM', 1, 1, 'San Marino', 'municipality'),
              ('SN', 1, 1, 'Senegal', 'region'),
              ('SO', 1, 1, 'Somalia', 'region'),
              ('SR', 1, 1, 'Suriname', 'district'),
              ('SS', 1, 1, 'South Sudan', 'state'),
              ('ST', 1, 1, 'Sao Tome and Principe', 'province'),
              ('SV', 1, 1, 'El Salvador', 'department'),
              ('SX', 1, 1, 'Sint Maarten (Dutch part)', NULL),
              ('SY', 1, 1, 'Syrian Arab Republic', 'province'),
              ('SZ', 1, 1, 'Eswatini', 'region'),
              ('TC', 1, 0, 'Turks and Caicos Islands', NULL),
              ('TD', 1, 1, 'Chad', 'region'),
              ('TF', 1, 0, 'French Southern Territories', NULL),
              ('TG', 1, 1, 'Togo', 'region'),
              ('TH', 1, 1, 'Thailand', 'province'),
              ('TJ', 1, 1, 'Tajikistan', 'capital territory'),
              ('TK', 1, 0, 'Tokelau', NULL),
              ('TL', 1, 1, 'Timor-Leste', 'municipality'),
              ('TM', 1, 1, 'Turkmenistan', 'region'),
              ('TN', 1, 1, 'Tunisia', 'governorate'),
              ('TO', 1, 1, 'Tonga', 'division'),
              ('TR', 1, 1, 'Turkey', 'province'),
              ('TT', 1, 1, 'Trinidad and Tobago', 'municipality'),
              ('TV', 1, 1, 'Tuvalu', 'town council'),
              ('TW', 1, 1, 'Taiwan', 'county'),
              ('TZ', 1, 1, 'Tanzania, United Republic of', 'region'),
              ('UA', 1, 1, 'Ukraine', 'republic'),
              ('UG', 1, 1, 'Uganda', 'district'),
              ('UM', 1, 1, 'United States Minor Outlying Islands', 'islands, groups of islands'),
              ('US', 1, 1, 'United States of America', 'state'),
              ('UY', 1, 1, 'Uruguay', 'department'),
              ('UZ', 1, 1, 'Uzbekistan', 'region'),
              ('VA', 1, 0, 'Holy See', NULL),
              ('VC', 1, 1, 'Saint Vincent and the Grenadines', 'parish'),
              ('VE', 1, 1, 'Venezuela (Bolivarian Republic of)', 'state'),
              ('VG', 1, 0, 'Virgin Islands (British)', NULL),
              ('VI', 1, 1, 'Virgin Islands (U.S.)', NULL),
              ('VN', 1, 1, 'Viet Nam', 'province'),
              ('VU', 1, 1, 'Vanuatu', 'province'),
              ('WF', 1, 1, 'Wallis and Futuna', ''),
              ('WS', 1, 1, 'Samoa', 'district'),
              ('XK', 1, 1, 'Republic of Kosovo', 'district'),
              ('YE', 1, 1, 'Yemen', 'governorate'),
              ('YT', 1, 0, 'Mayotte', NULL),
              ('ZA', 1, 1, 'South Africa', 'province'),
              ('ZM', 1, 1, 'Zambia', 'province'),
              ('ZW', 1, 1, 'Zimbabwe', 'province'))
AS SOURCE (CountryCode,
           IsActive,
           HasDivisions,
           CountryName,
           DivisionName)
ON TARGET.CountryCode = SOURCE.CountryCode
WHEN MATCHED THEN UPDATE SET TARGET.CountryName        = SOURCE.CountryName,
                             TARGET.DivisionName       = SOURCE.DivisionName,
                             TARGET.HasDivisions       = SOURCE.HasDivisions,
                             TARGET.IsActive           = SOURCE.IsActive
WHEN NOT MATCHED THEN INSERT (CountryCode,
                              CountryName,
                              DivisionName,
                              HasDivisions,
                              IsActive)
                      VALUES (SOURCE.CountryCode,
                              SOURCE.CountryName,
                              SOURCE.DivisionName,
                              SOURCE.HasDivisions,
                              SOURCE.IsActive);